version: '3'

networks:
  main_network:
    external: true

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - main_network