version: '3.2'

networks:
  main_network:
    external: true

services:
  places_remember:
    build: .
    restart: on-failure
    command: sh entrypoint.sh
    environment:
      DB_NAME: 'places_remember'
      DB_USER: 'docker'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_PASSWORD: 'LEW9gpVBMwu6'
    volumes:
      - ./assets:/opt/app/static
    networks:
      - main_network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./assets:/opt/app/static
    ports:
      - 80:80
    depends_on:
      - places_remember
    networks:
      - main_network
    secrets:
      - fullchain.pem
      - privkey.pem

secrets:
  fullchain.pem:
   external: true
  privkey.pem:
   external: true