version: '3'

networks:
  main_network:
    external: true

services:
  places_remember:
    build: .
    restart: always
    command: sh entrypoint.sh
    environment:
      DB_NAME: 'places_remember'
      DB_USER: 'docker'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_PASSWORD: 'LEW9gpVBMwu6'
    volumes:
      - .:/opt/app/:cached
    ports:
      - 8000:80
    networks:
      - main_network