FROM postgres:11

ENV POSTGIS_MAJOR 2.5
ENV POSTGIS_VERSION 2.5.2+dfsg-1~exp1.pgdg90+1

RUN apt-get update \
      && apt-cache showpkg postgresql-11-postgis-2.5\
      && apt-get install -y --no-install-recommends \
           postgresql-11-postgis-2.5 \
           postgresql-11-postgis-2.5-scripts \
           postgis \
      && rm -rf /var/lib/apt/lists/*

COPY init_db.sql /docker-entrypoint-initdb.d/