version: '3'

networks:
  main_network:
    external: true

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - main_network