CREATE USER docker WITH PASSWORD 'LEW9gpVBMwu6';
ALTER ROLE docker SUPERUSER;
CREATE DATABASE places_remember;
GRANT ALL PRIVILEGES ON DATABASE places_remember TO docker;
CREATE EXTENSION IF NOT EXISTS postgis;