# Generated by Django 2.2.12 on 2020-04-26 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='City name')),
                ('people_population', models.PositiveIntegerField(default=0, verbose_name='Population of people living in the city')),
            ],
        ),
        migrations.CreateModel(
            name='Remember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=512, verbose_name='Place of visit')),
                ('description', models.TextField(null=True, verbose_name='Description of remember')),
                ('date', models.DateField(verbose_name='Date of visit')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remember.City', verbose_name='City of visit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User own remember')),
            ],
        ),
    ]
