# Generated by Django 2.2.12 on 2020-05-03 12:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remember', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='remember',
            options={'verbose_name': 'Remember', 'verbose_name_plural': 'Remembers'},
        ),
        migrations.AddField(
            model_name='remember',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Coordinates of visit'),
        ),
    ]
